server:
  port: 8111
db: school
ip: 192.168.2.135
spring:
  application:
    name: studentApplication
  datasource:
#    druid:
    username: root
    password: root
    url: jdbc:mysql://${ip}:3306/${db}?charracterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${ip}:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.cang.dao: debug
    com.cang: warn