server:
  port: 8111
db: school
ip: 10.123.7.110
spring:
  application:
    name: studentApplication
  datasource:
#    druid:
    username: root
    password: root
    url: jdbc:mysql://${ip}:3306/${db}?charracterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${ip}:8848
#        namespace: hsa-oms.yml
feign:
  client:
    config:
      default:
        connectTimeout: 3000 #单位毫秒
        readTimeout: 12000 #单位毫秒

  #允许存在多个Feign调用相同Service的接口
 # main:
   # allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.cang.dao: debug
    com.cang: debug
