spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: studentApplicationTest
          uri: lb://studentApplication
          predicates:
            - Path=/api/student/**
          filters:
            - StripPrefix=1
        - id: teacherApplicationTest
          uri: lb://teacherApplication
          predicates:
            - Path=/api/teacher/**
          filters:
            - StripPrefix=1
    nacos:
      server-addr: 127.0.0.1:8848
server:
  port: 10000
