server:
  port: 10008
spring:
  application:
    name: kafkaconsumer
  kafka:
    consumer:
      group-id: defaultGroup
      # 是否自动提交offset
      enable-auto-commit: true
      # 提交offset延时(接收到消息后多久提交offset)
      auto-commit-interval: 1
      # none:只要有一个分区不存在已提交的offset,就抛出异常;
      auto-offset-reset: latest
      # 消费会话超时时间(超过这个时间consumer没有发送心跳,就会触发rebalance操作)
      properties:
        session:
          timeout:
            ms: 120000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 消费端监听的topic不存在时，项目启动会报错
    listener:
      missing-topics-fatal: false
